on: push

name: Create Release

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          run_id: 3613378250

      - run: ls '**/*.tar.gz'

      - run: gh release create v0.4.0 '**/*.tar.gz' '**/kindle_lemmas_dump_*'
        env:
          GH_TOKEN: ${{ github.token }}